Adding User&UserProfile to api
Artur-Leshko/NoReddit-backend pull request #1
Opened 2022-03-22 09:44 UTC by Artur-Leshko

2022-03-25 07:02 UTC, euseand commented on api/urls.py
> +urlpatterns = [
all patterns should follow next rule:
hostname/api/v1/route-name

2022-03-25 07:03 UTC, euseand commented on api/urls.py
> +    path('register/', signup, name='user_registration'),
/api/v1/auth/register

2022-03-25 07:03 UTC, euseand commented on api/urls.py
> +    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
/api/v1/auth/sign-in

2022-03-25 07:05 UTC, euseand commented on api/urls.py
> +    path('userprofile/', include('api.userprofile.urls')),
/api/v1/user/<user_id>/profile

2022-03-25 07:07 UTC, euseand commented on api/userprofile/serializers.py
> +        fields = ['username', 'email', 'is_admin']
should we provide user email in our api? seems unsecure

2022-03-25 07:11 UTC, euseand commented on api/userprofile/views.py
> +        userprofile.delete()
simply delete profile? so we can have user accounts without profile in application?

2022-03-25 07:11 UTC, euseand commented on api/userprofile/views.py
> +            raise Http404
you should provide some custom exceptions and responses

2022-03-25 07:13 UTC, euseand commented on api/views.py
> +                user = User.objects.create(email=data['email'], username=data['username'])
what if the email or username already occupied?

2022-03-25 07:14 UTC, euseand commented on api/views.py
> +            return JsonResponse({ 'refresh': str(refreshToken), 'access': str(refreshToken.access_token), })
shouldn't it happen on sign-in?

2022-03-25 07:15 UTC, euseand commented on api/views.py
> +        except IntegrityError:
why wrap most of the method while you can raise custom exception?

2022-03-25 07:16 UTC, euseand commented on userprofile/models.py
> +            raise ValueError("Useranem is required field!")
typo

2022-03-25 07:19 UTC, euseand requested changes
provide solutions following the comments

2022-03-28 20:46 UTC, Artur-Leshko commented on api/urls.py
> +urlpatterns = [
added api version

2022-03-28 20:48 UTC, Artur-Leshko commented on api/urls.py
> +    path('register/', signup, name='user_registration'),
changed to /api/v1/auth/sign-up/

2022-03-28 20:54 UTC, Artur-Leshko commented on api/urls.py
> +    path('userprofile/', include('api.userprofile.urls')),
path was changed

2022-03-28 21:02 UTC, Artur-Leshko commented on api/userprofile/serializers.py
> +        fields = ['username', 'email', 'is_admin']
remove email from UserProfile serializer

2022-03-28 21:04 UTC, Artur-Leshko commented on api/userprofile/views.py
> +        userprofile.delete()
now deleting User model that leads deleting UserProfile model

2022-03-28 21:39 UTC, Artur-Leshko commented on api/userprofile/views.py
> +            raise Http404
implemented CustomApiExeption class

2022-03-28 22:02 UTC, Artur-Leshko commented on api/views.py
> +        except IntegrityError:
method was rewritten

2022-03-28 22:10 UTC, Artur-Leshko commented on api/views.py
> +            return JsonResponse({ 'refresh': str(refreshToken), 'access': str(refreshToken.access_token), })
method was rewritten, now it returns only success message

2022-04-01 08:27 UTC, euseand approved these changes

2022-04-04 19:10 UTC, merged